// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secim2028.Data;

#nullable disable

namespace Secim2028.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240523231707_User")]
    partial class User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secim2028.Models.AdayCumhurbaskani", b =>
                {
                    b.Property<int>("AdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdayId"));

                    b.Property<string>("AdayAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiyasiPartiId")
                        .HasColumnType("int");

                    b.HasKey("AdayId");

                    b.HasIndex("SiyasiPartiId");

                    b.ToTable("Adaylar");
                });

            modelBuilder.Entity("Secim2028.Models.Il", b =>
                {
                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlId");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("Secim2028.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceId"));

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlceId");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("Secim2028.Models.Ittifak", b =>
                {
                    b.Property<int>("IttifakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IttifakId"));

                    b.Property<string>("IttifakAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IttifakId");

                    b.ToTable("Ittifaklar");
                });

            modelBuilder.Entity("Secim2028.Models.OyAday", b =>
                {
                    b.Property<int>("OyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OyId"));

                    b.Property<int>("AdayId")
                        .HasColumnType("int");

                    b.Property<int>("OySayisi")
                        .HasColumnType("int");

                    b.Property<int>("SandikId")
                        .HasColumnType("int");

                    b.HasKey("OyId");

                    b.HasIndex("AdayId");

                    b.HasIndex("SandikId");

                    b.ToTable("AdayOylar");
                });

            modelBuilder.Entity("Secim2028.Models.OyParti", b =>
                {
                    b.Property<int>("OyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OyId"));

                    b.Property<int>("OySayisi")
                        .HasColumnType("int");

                    b.Property<int>("SandikId")
                        .HasColumnType("int");

                    b.Property<int>("SiyasiPartiId")
                        .HasColumnType("int");

                    b.HasKey("OyId");

                    b.HasIndex("SandikId");

                    b.HasIndex("SiyasiPartiId");

                    b.ToTable("PartiOylar");
                });

            modelBuilder.Entity("Secim2028.Models.Sandik", b =>
                {
                    b.Property<int>("SandikId")
                        .HasColumnType("int");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<int>("SandikNo")
                        .HasColumnType("int");

                    b.HasKey("SandikId");

                    b.HasIndex("IlceId");

                    b.ToTable("Sandiklar");
                });

            modelBuilder.Entity("Secim2028.Models.SiyasiParti", b =>
                {
                    b.Property<int>("SiyasiPartiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiyasiPartiId"));

                    b.Property<int?>("IttifakId")
                        .HasColumnType("int");

                    b.Property<string>("SiyasiPartiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiyasiPartiKisaltma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiyasiPartiId");

                    b.HasIndex("IttifakId");

                    b.ToTable("Partiler");
                });

            modelBuilder.Entity("Secim2028.Models.User", b =>
                {
                    b.Property<int>("uID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uID"));

                    b.Property<string>("hashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Secim2028.Models.AdayCumhurbaskani", b =>
                {
                    b.HasOne("Secim2028.Models.SiyasiParti", "SiyasiParti")
                        .WithMany("CumhurbaskaniAdayi")
                        .HasForeignKey("SiyasiPartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiyasiParti");
                });

            modelBuilder.Entity("Secim2028.Models.Ilce", b =>
                {
                    b.HasOne("Secim2028.Models.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("Secim2028.Models.OyAday", b =>
                {
                    b.HasOne("Secim2028.Models.AdayCumhurbaskani", "CumhurbaskaniAdayi")
                        .WithMany("OyAdays")
                        .HasForeignKey("AdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secim2028.Models.Sandik", "Sandik")
                        .WithMany("OyAdaylar")
                        .HasForeignKey("SandikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CumhurbaskaniAdayi");

                    b.Navigation("Sandik");
                });

            modelBuilder.Entity("Secim2028.Models.OyParti", b =>
                {
                    b.HasOne("Secim2028.Models.Sandik", "Sandik")
                        .WithMany("OyPartiler")
                        .HasForeignKey("SandikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secim2028.Models.SiyasiParti", "SiyasiParti")
                        .WithMany()
                        .HasForeignKey("SiyasiPartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandik");

                    b.Navigation("SiyasiParti");
                });

            modelBuilder.Entity("Secim2028.Models.Sandik", b =>
                {
                    b.HasOne("Secim2028.Models.Ilce", "Ilce")
                        .WithMany("Sandiklar")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("Secim2028.Models.SiyasiParti", b =>
                {
                    b.HasOne("Secim2028.Models.Ittifak", "Ittifak")
                        .WithMany("SiyasiPartiler")
                        .HasForeignKey("IttifakId");

                    b.Navigation("Ittifak");
                });

            modelBuilder.Entity("Secim2028.Models.AdayCumhurbaskani", b =>
                {
                    b.Navigation("OyAdays");
                });

            modelBuilder.Entity("Secim2028.Models.Il", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("Secim2028.Models.Ilce", b =>
                {
                    b.Navigation("Sandiklar");
                });

            modelBuilder.Entity("Secim2028.Models.Ittifak", b =>
                {
                    b.Navigation("SiyasiPartiler");
                });

            modelBuilder.Entity("Secim2028.Models.Sandik", b =>
                {
                    b.Navigation("OyAdaylar");

                    b.Navigation("OyPartiler");
                });

            modelBuilder.Entity("Secim2028.Models.SiyasiParti", b =>
                {
                    b.Navigation("CumhurbaskaniAdayi");
                });
#pragma warning restore 612, 618
        }
    }
}
