name: Publish 🚀🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: Secim2028api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"


jobs: 
  publish:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'


    - name: Restore
      run: dotnet restore ./Secim2028.sln

    - name: build
      run: dotnet build ./Secim2028.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Secim2028.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'


    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/appsettings.json'
      env:
          ConnectionStrings.dev: ${{ secrets.MSSQL_DEV_CONNECTION_STRING }}

    - name: Deployement
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
